TEMP_MAINTAINED_EXCLUSIONS = {
    "1Password": ["1password-browsersupport.exe", "1password.exe", "op-ssh-sign.exe"],
    "Altiris by Symantec": ["aexnsagent.exe"],
    "Appsense": ["amagentassist.exe", "empshost.exe", "emuser.exe", "emuserlogoff.exe", "cca.exe"],
    "AVAST": ["avastsvc.exe"],
    "Avira": ["avira.exe"],
    "Azure Devops": ["agent.worker.exe", "windowsazureguestagent.exe"],
    "Cisco AnyConnect VPN": ["acumbrellaagent.exe", "acwebhelper.exe", "acnvmagent.exe", "vpnagent.exe"],
    "Cisco WebEx": ["atmgr.exe", "ciscocollabhost.exe", "ciscowebextstart.exe", "ptoneclk.exe", "webexmta.exe", "wbxreport.exe"],
    "Citrix AppDNA": ["ossnapshot.exe"],
    "Citrix Cloud Connector": ["configsyncservice.exe", "xaxdcloudproxy.exe"],
    "Citrix EdgeSight Server": ["fbserver.exe", "rscorsvc.exe"],
    "Citrix ICA Client": ["selfservice.exe", "brokerservice.exe", "cpsvc.exe", "picasvc2.exe"],
    "Citrix Provisioning Server": ["bndevice.exe", "bnpxe.exe", "bntftp.exe", "inventory.exe", "mgmtdaemon.exe", "notifier.exe", "pvstsb.exe", "soapserver.exe", "streamprocess.exe", "streamservice.exe"],
    "Citrix Sessions Recording": ["ssrecplayer.exe", "ssrecagent.exe", "ssrecagentwrapper.exe", "icldb.exe", "iclstat.exe", "ssrecanalyticsservice.exe", "ssrecserverconsole.exe", "ssrecstoragemanager.exe", "ssrecwebsocketserverexe"],
    "Citrix XenApp": ["imaadvancesrv.exe", "lmasrv.exe"],
    "Commvault": ["cldbengine.exe"],
    "Control Up": ["cuagent.exe"],
    "Crashplan": ["crashplanservice.exe", "code42service.exe"],
    "Diebold Warsaw": ["core.exe"],
    "Digital Guardian": ["dgagent.exe"],
    "Domain Controller": ["dfsrs.exe", "dns.exe"],
    "HP Touchpoint": ["lhagent.exe", "coreprovider.exe", "touchpointanalyticsclientservice.exe"],
    "Hyper-V": ["vmcompute.exe", "vmms.exe", "vmsp.exe", "vmwp.exe"],
    "IBM": ["tlmagent.exe"],
    "IIS": ["w3wp.exe", "w3wp.exe"],
    "Kaspersky": ["avp.exe", "klnagent.exe"],
    "Lakeside Software - Systrack": ["vc_redist.x86.exe", "vc_redist.x64.exe", "jetcomp.exe", "lsiagent.exe", "lsisupervisor.exe"],
    "Malwarebytes": ["mbam.exe"],
    "ManageEngine Desktop Central": ["dcappcontrol.exe", "dcinventory.exe", "dcondemand.exe", "dcconfig.exe"],
    "McAfee": ["macmnsvc.exe", "mcscript_inuse.exe", "mfeatp.exe", "mfeesp.exe", "mfetp.exe"],
    "McAfee Trellix SolidCore": ["auditmanagerservice.exe", "enginemain.exe", "fimcli.exe"],
    "Microsoft Exchange Server": ["edgetransport.exe", "noderunner.exe"],
    "Microsoft Forefront": ["fscrealtimescanner.exe"],
    "Microsoft Intune": ["omsvchost2.exe", "omsvchost.exe"],
    "Microsoft Office": ["officeclicktorun.exe"],
    "Microsoft OneDrive": ["onedrive.exe"],
    "Microsoft OneNote": ["onenotem.exe", "onenote.exe"],
    "Microsoft Security Client": ["msseces.exe"],
    "Microsoft SQL Server": ["clussvc.exe", "rhs.exe", "sqlserver.exe", "msmdsrv.exe", "sqldumper.exe"],
    "Microsoft Teams": ["teams.exe"],
    "Microsoft Windows Defender": ["mssense.exe", "sensecncproxy.exe", "senseir.exe", "sensesampleuploader.exe"],
    "NetScout": ["nsprobe.exe"],
    "SCCM": ["cmupdate.exe", "sitecomp.exe", "smsexec.exe", "smssqlbbkup.exe", "smswriter.exe", "ccmexec.exe", "ccmrepair.exe", "ccmsetup.exe", "ccmexec.exe"],
    "SolarWinds N-Able Technologies": ["basupsrvc.exe", "basupcnfg.exe", "thirdapartypatch.exe"],
    "SolarWinds Samanage Agent": ["samanageagent.exe", "tnswind.exe"],
    "Sophos": ["mgntsvc.exe", "patchdataloader.exe"],
    "Splunk": ["splunk-winevtlog.exe", "splunkd.exe"],
    "Symantect Endpoint Protection": ["smc.exe", "ccsvchst.exe", "brkrprcs64.exe", "edpa.exe"],
    "Tanium": ["taniumclient.exe", "taniumdetectengine.exe", "taniumdetect.exe", "taniumendpointindex.exe", "end-user-notificiations.exe", "taniumclient.exe"],
    "Trend Micro - Apex One": ["tmbmsrv.exe", "tmiacagentsvc.exe", "atasagent.exe", "esclient.exe", "eseframeworkhost.exe", "eseserviceshell.exe", "ivpagent.exe"],
    "VEEAM": ["veeamagent.exe", "veeamagent64.exe"],
    "VMWare": ["daasagent.exe"],
    "VSE": ["mcshield.exe", "shstat.exe", "mfeann.exe"],
    "Websense": ["dserui.exe", "endpointclassifier.exe", "kvoop.exe", "wepsvc.exe", "dserui.exe"],
    "X1 Search": ["x1.exe"]
}
